<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Rokun1n.TaskPlanner.Domain.Logic\**" />
    <Compile Remove="Rokun1n.TaskPlanner.Domain.Models\**" />
    <Compile Remove="Rokun1n.GuessNumber\**" />
    <EmbeddedResource Remove="Rokun1n.TaskPlanner.Domain.Logic\**" />
    <EmbeddedResource Remove="Rokun1n.TaskPlanner.Domain.Models\**" />
    <EmbeddedResource Remove="Rokun1n.GuessNumber\**" />
    <None Remove="Rokun1n.TaskPlanner.Domain.Logic\**" />
    <None Remove="Rokun1n.TaskPlanner.Domain.Models\**" />
    <None Remove="Rokun1n.GuessNumber\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Rokun1n.TaskPlanner.Domain.Logic\Rokun1n.TaskPlanner.Domain.Logic.csproj" />
    <ProjectReference Include="Rokun1n.TaskPlanner.Domain.Models\Rokun1n.TaskPlanner.Domain.Models.csproj" />
  </ItemGroup>

</Project>
